FROM node:lts as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as prod
RUN mkdir /app
COPY --from=build /app/dist /app
COPY local.conf /etc/nginx/nginx.conf